# Generated by Django 4.2.13 on 2024-08-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_category_image_and_more'),
        ('products', '0003_remove_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products_category', to='categories.category'),
        ),
    ]
